# Generated by Django 4.2.23 on 2025-08-26 09:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/<django.db.models.fields.CharField>/files'), upload_to='')),
            ],
        ),
    ]
