# Generated by Django 5.0.3 on 2025-12-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcomponent',
            name='props',
        ),
    ]
