# Generated by Django 5.0.3 on 2026-01-07 12:20

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_dashboardcomponent_props'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('image', models.ImageField(upload_to=api.models.project_directory_path)),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
