# Generated by Django 4.2.23 on 2026-01-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagecomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantsComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
