# Generated by Django 4.2.23 on 2025-09-19 08:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_dashboard_dashboardcomponent_eventlog_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="file",
            field=models.FileField(upload_to=api.models.project_directory_path),
        ),
    ]
