# Generated by Django 4.2.23 on 2025-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_eventlog_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
