# Generated by Django 4.2.23 on 2026-01-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_variantscomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantscomponent',
            name='automatic_loading',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='variantscomponent',
            name='leading_object_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
