# Generated by Django 4.2.23 on 2025-09-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_dashboard_created_at_project_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="name",
            field=models.CharField(default="dashboard", max_length=30),
            preserve_default=False,
        ),
    ]
