# Generated by Django 4.2.23 on 2026-02-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_processareacomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStatisticsComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('show_num_events', models.BooleanField(default=True)),
                ('show_num_activities', models.BooleanField(default=True)),
                ('show_num_objects', models.BooleanField(default=True)),
                ('show_num_object_types', models.BooleanField(default=True)),
                ('show_earliest_timestamp', models.BooleanField(default=False)),
                ('show_newest_timestamp', models.BooleanField(default=False)),
                ('show_duration', models.BooleanField(default=False)),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
