# Generated by Django 4.2.23 on 2026-02-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ocdfgcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocdfgcomponent',
            name='initial_interaction_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocdfgcomponent',
            name='show_controls',
            field=models.BooleanField(default=True),
        ),
    ]
