# Generated by Django 4.2.23 on 2026-04-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ocdfgcomponent_initial_interaction_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLQueryComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('query_text', models.TextField(blank=True, null=True)),
                ('saved_query_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
