# Generated by Django 4.2.23 on 2026-02-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ocdfgcomponent_initial_interaction_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotemModelComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('initial_tau', models.FloatField(blank=True, default=0.9, null=True)),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
