# Generated by Django 4.2.23 on 2026-05-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ocdfgcomponent_initial_interaction_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantscomponent',
            name='extraction',
            field=models.CharField(blank=True, default='leading_1hop', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='variantscomponent',
            name='iso',
            field=models.CharField(blank=True, default='wl+vf2', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='variantscomponent',
            name='timeout_s',
            field=models.FloatField(blank=True, default=10.0, null=True),
        ),
    ]
