# Generated by Django 4.2.23 on 2026-04-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sqlquerycomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCELQueryComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('query', models.TextField(default='SELECT * FROM events LIMIT 10')),
            ],
            bases=('api.dashboardcomponent',),
        ),
        migrations.RemoveField(
            model_name='sqlquerycomponent',
            name='query_text',
        ),
        migrations.RemoveField(
            model_name='sqlquerycomponent',
            name='saved_query_name',
        ),
        migrations.AddField(
            model_name='sqlquerycomponent',
            name='query',
            field=models.TextField(default='SELECT * FROM data LIMIT 10'),
        ),
    ]
