# Generated by Django 4.2.23 on 2026-06-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_variantscomponent_extraction_variantscomponent_iso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterStackComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('filter_stack_json', models.JSONField(blank=True, default=list)),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
