# Generated by Django 4.2.23 on 2026-06-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_variantscomponent_extraction_variantscomponent_iso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOCDFGComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('show_controls', models.BooleanField(default=True)),
                ('initial_interaction_locked', models.BooleanField(default=True)),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
