# Generated by Django 4.2.23 on 2026-06-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_variantscomponent_extraction_variantscomponent_iso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCDottedChartComponent",
            fields=[
                (
                    "dashboardcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.dashboardcomponent",
                    ),
                ),
                ("file_id", models.PositiveIntegerField(blank=True, null=True)),
                ("x_axis", models.CharField(default="time", max_length=255)),
                ("y_axis", models.CharField(default="activity", max_length=255)),
                ("color_by", models.CharField(default="activity", max_length=255)),
                ("shape_by", models.CharField(default="none", max_length=255)),
                (
                    "row_order",
                    models.CharField(default="first_occurrence", max_length=32),
                ),
                ("max_points", models.PositiveIntegerField(default=10000)),
                ("show_minimap", models.BooleanField(default=True)),
                ("show_controls", models.BooleanField(default=True)),
            ],
            bases=("api.dashboardcomponent",),
        ),
    ]
