# Generated by Django 4.2.23 on 2026-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_newocdfgcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newocdfgcomponent',
            name='layout_direction',
            field=models.CharField(choices=[('TB', 'Top to Bottom'), ('LR', 'Left to Right')], default='TB', max_length=2),
        ),
    ]
