# Generated by Django 4.2.23 on 2026-06-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ocelquerycomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieChartComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('query', models.TextField(default='SELECT * FROM events LIMIT 10')),
                ('ring_text', models.CharField(blank=True, default='', max_length=200)),
                ('chart_type', models.CharField(default='donut', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('label_column', models.CharField(blank=True, default='', max_length=100)),
                ('value_column', models.CharField(blank=True, default='', max_length=100)),
                ('show_legend', models.BooleanField(default=True)),
                ('show_tooltip', models.BooleanField(default=True)),
            ],
            bases=('api.dashboardcomponent',),
        ),
        migrations.DeleteModel(
            name='OCELQueryComponent',
        ),
    ]
