# Generated by Django 4.2.23 on 2026-06-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_ocdottedchartcomponent"),
        ("api", "0012_add_layout_direction_to_new_ocdfg_component"),
    ]

    operations = []
