# Generated by Django 4.2.23 on 2026-07-01 14:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_oc_dotted_chart_new_ocdfg'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCCNComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('relative_occurrence_threshold', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('show_controls', models.BooleanField(default=True)),
                ('initial_interaction_locked', models.BooleanField(default=True)),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
