# Generated by Django 4.2.23 on 2026-07-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_merge_oc_dotted_chart_new_ocdfg"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCPNComponent",
            fields=[
                (
                    "dashboardcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.dashboardcomponent",
                    ),
                ),
                (
                    "automatic_loading",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("timeout_s", models.FloatField(blank=True, default=30.0, null=True)),
            ],
            bases=("api.dashboardcomponent",),
        ),
    ]
