# Generated by Django 4.2.23 on 2026-07-07 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0013_merge_oc_dotted_chart_new_ocdfg"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("TOTEM", "TOTeM"), ("OCCN", "OCCN")], max_length=20
                    ),
                ),
                ("content_json", models.JSONField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "asset_type"],
                        name="api_project_project_5470a3_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectasset",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_project_asset_name"
            ),
        ),
    ]
