# Generated by Django 4.2.23 on 2026-07-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_oc_dotted_chart_new_ocdfg'),
        ('api', '0013_totemminercomponent'),
    ]

    operations = [
    ]
