# Generated by Django 4.2.23 on 2026-07-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_piechartcomponent_delete_ocelquerycomponent'),
        ('api', '0013_merge_oc_dotted_chart_new_ocdfg'),
    ]

    operations = [
    ]
