# Generated by Django 4.2.23 on 2026-07-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20260715_1057'),
        ('api', '0014_projectasset_projectasset_unique_project_asset_name'),
    ]

    operations = [
    ]
