# Generated by Django 4.2.23 on 2026-07-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_occncomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='occncomponent',
            name='layout_direction',
            field=models.CharField(choices=[('TB', 'Top to Bottom'), ('LR', 'Left to Right')], default='LR', max_length=2),
        ),
        migrations.AddField(
            model_name='occncomponent',
            name='object_types',
            field=models.TextField(blank=True, default=''),
        ),
    ]
