# Generated by Django 4.2.23 on 2026-07-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_projectasset_projectasset_unique_project_asset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_logs",
                to="api.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
