# Generated by Django 4.2.23 on 2026-07-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_projectasset_projectasset_unique_project_asset_name'),
        ('api', '0015_occncomponent_layout_direction_and_more'),
    ]

    operations = [
    ]
