# Generated by Django 4.2.23 on 2026-07-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_filter_stack_component'),
        ('api', '0016_merge_projectasset_occncomponent'),
    ]

    operations = [
    ]
