# Generated by Django 4.2.23 on 2026-07-30 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20260716_1657'),
        ('api', '0016_merge_projectasset_occncomponent'),
    ]

    operations = [
    ]
