# Generated by Django 4.2.23 on 2026-08-15 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_projectasset_occncomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='processareacomponent',
            name='algorithm',
            field=models.CharField(choices=[('mlpa', 'MLPA (temporal)'), ('advanced', 'Advanced (resource indicators)')], default='advanced', max_length=16),
        ),
        migrations.AddField(
            model_name='processareacomponent',
            name='alpha',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='processareacomponent',
            name='beta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='processareacomponent',
            name='w_cardinality',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='processareacomponent',
            name='w_divergence',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='processareacomponent',
            name='w_temporal',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
