# Generated by Django 4.2.23 on 2026-07-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20260723_0954'),
        ('api', '0016_merge_projectasset_occncomponent'),
    ]

    operations = [
    ]
