# Generated by Django 4.2.23 on 2026-08-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260729_1644'),
        ('api', '0017_processareacomponent_algorithm_and_more'),
    ]

    operations = [
    ]
