# Generated by Django 4.2.23 on 2026-08-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_merge_20260730_0201"),
        ("api", "0018_merge_20260826_1334"),
    ]

    operations = []
