# Generated by Django 4.2.23 on 2026-08-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_merge_0014_oceleditorsession_0018_merge_20260826_1334"),
        ("api", "0019_merge_0014_ocpncomponent_0018_merge_20260826_1334"),
        ("api", "0019_merge_20260826_1506"),
        ("api", "0019_merge_20260826_1511"),
        ("api", "0019_merge_20260826_1541"),
    ]

    operations = []
