# Generated by Django 4.2.23 on 2026-08-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_merge_20260826_2006"),
        ("api", "0020_merge_20260826_2007"),
    ]

    operations = []
