# Generated by Django 4.2.23 on 2026-08-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20260827_0735'),
        ('api', '0021_merge_20260827_0738'),
    ]

    operations = [
    ]
