# Generated by Django 4.2.23 on 2026-08-29 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20260829_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlQueryComponent',
            fields=[
                ('dashboardcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.dashboardcomponent')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('query', models.TextField(default='SELECT activity, count(*) AS n FROM events GROUP BY activity')),
                ('expected_result', models.TextField(blank=True, default=None, null=True)),
                ('row_limit', models.PositiveIntegerField(default=25)),
            ],
            bases=('api.dashboardcomponent',),
        ),
    ]
