# Generated by Django 4.2.23 on 2026-08-27 20:02

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0022_merge_20260827_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecomponent",
            name="image_alignment",
            field=models.CharField(default="center", max_length=30),
        ),
        migrations.AddField(
            model_name="imagecomponent",
            name="image_fit",
            field=models.CharField(default="contain", max_length=20),
        ),
        migrations.AlterField(
            model_name="imagecomponent",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.project_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="projectasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("TOTEM", "TOTeM"),
                    ("OCCN", "OCCN"),
                    ("OCPN", "OCPN"),
                    ("OCDFG", "OC-DFG"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ImageAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(upload_to=api.models.image_asset_directory_path),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_assets",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="imagecomponent",
            name="image_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard_components",
                to="api.imageasset",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageasset",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_project_image_asset_name"
            ),
        ),
    ]
