# Generated by Django 4.2.23 on 2026-08-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20260829_2142'),
    ]

    # The SQL query component table was already created upstream by
    # 0010_sqlquerycomponent (as `SQLQueryComponent`) and reshaped by 0011.
    # Django's model registry is case-insensitive, so this branch's
    # `SqlQueryComponent` maps onto that same `api_sqlquerycomponent` table
    # rather than being a distinct model. Re-creating it here would fail with
    # "table already exists" once this branch is merged with main, so the
    # field changes are applied by 0025 as ALTERs instead.
    operations = []
