# Generated by Django 4.2.23 on 2026-09-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20260827_0755'),
        ('api', '0023_imagecomponent_image_alignment_and_more'),
    ]

    operations = [
    ]
