# Generated by Django 4.2.23 on 2026-09-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_imagecomponent_image_alignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantscomponent",
            name="business_activities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="variantscomponent",
            name="business_object_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
