# Generated by Django 4.2.23 on 2026-09-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_imagecomponent_image_alignment_and_more'),
        ('api', '0023_sqlquerycomponent'),
    ]

    operations = [
    ]
