# Generated by Django 4.2.23 on 2026-09-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_variantscomponent_resource_aware'),
        ('api', '0025_sqlquerycomponent_expected_result_and_more'),
    ]

    operations = [
    ]
