# Generated by Django 4.2.23 on 2026-09-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20260910_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
