# Generated by Django 4.2.23 on 2026-09-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_merge_20260910_1400"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sqlquerycomponent",
            name="expected_result",
        ),
        migrations.AddField(
            model_name="piechartcomponent",
            name="query_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.projectasset",
            ),
        ),
        migrations.AddField(
            model_name="sqlquerycomponent",
            name="query_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.projectasset",
            ),
        ),
        migrations.AlterField(
            model_name="projectasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("TOTEM", "TOTeM"),
                    ("OCCN", "OCCN"),
                    ("OCPN", "OCPN"),
                    ("OCDFG", "OC-DFG"),
                    ("QUERY", "SQL Query"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ScatterPlotComponent",
            fields=[
                (
                    "dashboardcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.dashboardcomponent",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "query",
                    models.TextField(
                        default="SELECT count(*) AS x, count(DISTINCT activity) AS y FROM events"
                    ),
                ),
                ("x_column", models.CharField(blank=True, default="", max_length=100)),
                ("y_column", models.CharField(blank=True, default="", max_length=100)),
                (
                    "series_column",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("x_label", models.CharField(blank=True, default="", max_length=100)),
                ("y_label", models.CharField(blank=True, default="", max_length=100)),
                (
                    "query_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.projectasset",
                    ),
                ),
            ],
            bases=("api.dashboardcomponent",),
        ),
        migrations.CreateModel(
            name="KpiComponent",
            fields=[
                (
                    "dashboardcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.dashboardcomponent",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "query",
                    models.TextField(default="SELECT count(*) AS value FROM events"),
                ),
                (
                    "value_column",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("prefix", models.CharField(blank=True, default="", max_length=50)),
                ("suffix", models.CharField(blank=True, default="", max_length=50)),
                ("decimals", models.PositiveSmallIntegerField(default=0)),
                (
                    "query_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.projectasset",
                    ),
                ),
            ],
            bases=("api.dashboardcomponent",),
        ),
        migrations.CreateModel(
            name="BarChartComponent",
            fields=[
                (
                    "dashboardcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.dashboardcomponent",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "query",
                    models.TextField(
                        default="SELECT activity AS label, count(*) AS value FROM events GROUP BY activity ORDER BY value DESC"
                    ),
                ),
                (
                    "label_column",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "value_column",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("horizontal", models.BooleanField(default=False)),
                ("show_values", models.BooleanField(default=False)),
                (
                    "query_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.projectasset",
                    ),
                ),
            ],
            bases=("api.dashboardcomponent",),
        ),
    ]
