# Generated by Django 4.2.23 on 2026-09-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_project_display_name'),
        ('api', '0027_sql_query_assets_and_chart_components'),
    ]

    operations = [
    ]
