# Generated by Django 4.2.23 on 2026-09-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_ocdfgcomponent'),
        ('api', '0027_sql_query_assets_and_chart_components'),
    ]

    operations = [
    ]
