# Generated by Django 4.2.23 on 2026-09-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20260914_1612'),
        ('api', '0028_merge_20260915_1515'),
    ]

    operations = [
    ]
