# Generated by Django 4.2.23 on 2026-09-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20260903_1213'),
        ('api', '0029_merge_20260917_1501'),
    ]

    operations = [
    ]
