# Generated by Django 4.2.23 on 2026-09-22 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_merge_20260917_1501"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCHandoverComponent",
            fields=[
                (
                    "dashboardcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.dashboardcomponent",
                    ),
                ),
                ("show_controls", models.BooleanField(default=True)),
                ("automatic_loading", models.BooleanField(default=False)),
                (
                    "method",
                    models.CharField(
                        choices=[("oc", "Object-centric"), ("flattened", "Flattened")],
                        default="oc",
                        max_length=16,
                    ),
                ),
                ("resource_types", models.JSONField(blank=True, default=list)),
                ("businessobject_types", models.JSONField(blank=True, default=list)),
                ("case_type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "flat_resource_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("max_gap", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "normalization",
                    models.CharField(default="by_arcs_in_eog", max_length=32),
                ),
                (
                    "normalization_scope",
                    models.CharField(default="global", max_length=16),
                ),
                ("parallel_filter_enabled", models.BooleanField(default=False)),
                (
                    "parallel_threshold",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("min_parallel_observations", models.PositiveIntegerField(default=1)),
                ("cluster_by_ot", models.BooleanField(default=False)),
                (
                    "view_mode",
                    models.CharField(
                        choices=[
                            ("graph", "Graph"),
                            ("table", "Table"),
                            ("log", "Log"),
                        ],
                        default="graph",
                        max_length=8,
                    ),
                ),
            ],
            bases=("api.dashboardcomponent",),
        ),
        migrations.CreateModel(
            name="ResourceProfilingComponent",
            fields=[
                (
                    "dashboardcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.dashboardcomponent",
                    ),
                ),
                ("show_controls", models.BooleanField(default=True)),
                ("automatic_loading", models.BooleanField(default=False)),
                ("resource_types", models.JSONField(blank=True, default=list)),
                ("business_object_types", models.JSONField(blank=True, default=list)),
                ("feature_groups", models.JSONField(blank=True, default=list)),
                ("tooltip_feature_groups", models.JSONField(blank=True, default=list)),
                ("compute_clusters", models.BooleanField(default=True)),
                (
                    "cluster_method",
                    models.CharField(
                        choices=[
                            ("kmeans", "K-Means"),
                            ("agglomerative", "Agglomerative"),
                            ("hdbscan", "HDBSCAN"),
                        ],
                        default="hdbscan",
                        max_length=16,
                    ),
                ),
                ("n_clusters", models.PositiveIntegerField(default=3)),
                ("min_cluster_size", models.PositiveIntegerField(default=2)),
                (
                    "distance_metric",
                    models.CharField(
                        choices=[
                            ("euclidean", "Euclidean"),
                            ("hellinger", "Hellinger"),
                        ],
                        default="euclidean",
                        max_length=16,
                    ),
                ),
                (
                    "view_mode",
                    models.CharField(
                        choices=[("graph", "Graph"), ("table", "Table")],
                        default="graph",
                        max_length=8,
                    ),
                ),
            ],
            bases=("api.dashboardcomponent",),
        ),
    ]
