"""
Django settings for totem_backend project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

try:
    import whitenoise  # noqa: F401
    HAS_WHITENOISE = True
except ImportError:
    HAS_WHITENOISE = False


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Writable runtime data (SQLite DB, uploaded logs, result cache). Defaults to
# BASE_DIR for development and server deployments. The Electron app passes
# TOTEM_DATA_DIR=<per-user app data folder> because inside a packaged (and
# code-signed) app bundle BASE_DIR is read-only and must never be mutated.
DATA_DIR = Path(os.environ.get('TOTEM_DATA_DIR') or BASE_DIR)
DATA_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 't')

# Local / Electron mode — set LOCAL_MODE=1 in the environment to enable guest auto-login
LOCAL_MODE = os.environ.get('LOCAL_MODE', '0') == '1'


def _local_secret_key() -> str:
    """Per-installation secret for the desktop app.

    JWTs are signed with SECRET_KEY, so a key shared by every install would
    let anyone mint tokens for any user id. Generate one on first launch and
    keep it next to the database in DATA_DIR.
    """
    from django.core.management.utils import get_random_secret_key

    key_file = DATA_DIR / '.secret_key'
    try:
        if key_file.exists():
            existing = key_file.read_text(encoding='utf-8').strip()
            if existing:
                return existing
        key = get_random_secret_key()
        key_file.write_text(key, encoding='utf-8')
        try:
            os.chmod(key_file, 0o600)
        except OSError:
            pass
        return key
    except OSError:
        # Unwritable data dir: fall back to a process-lifetime key. Sessions
        # won't survive a restart, but nothing is shared across installs.
        return get_random_secret_key()


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if LOCAL_MODE:
        SECRET_KEY = _local_secret_key()
    elif DEBUG:
        # Development fallback only — never used when DEBUG is off.
        SECRET_KEY = 'django-insecure-*0lbvark4r$*=svt+$-(n!*&mwk$rk4g$azq^e6@9_+mg^ilsg'
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            'SECRET_KEY environment variable must be set when DEBUG is off.'
        )

# Allowed hosts configuration
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        '0.0.0.0',
        '.railway.app',
        '.up.railway.app',
        '.vercel.app',
    ]

# In production on Railway, ensure railway host is permitted
if os.environ.get('RAILWAY_STATIC_URL') or os.environ.get('RAILWAY_ENVIRONMENT'):
    if '.railway.app' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('.railway.app')
    if '.up.railway.app' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('.up.railway.app')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_extensions',  # seems not to be needed anymore
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'api',
    'authentification',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]
if HAS_WHITENOISE:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')

MIDDLEWARE.extend([
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
])

ROOT_URLCONF = 'totem_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'totem_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL and dj_database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DATA_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
if HAS_WHITENOISE:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cross-origin browser access is opt-in. Only the origins in
# CORS_ALLOWED_ORIGINS (default: the local dev frontend; the Electron app
# passes its own bundled-frontend origin) may call the API with credentials.
# The old default of "allow all" meant any website open in the user's browser
# could talk to the desktop app's local API (which auto-logs-in as Guest).
CORS_ORIGIN_ALLOW_ALL = os.environ.get('CORS_ORIGIN_ALLOW_ALL', '0') == '1'
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
    "content-type",
]

cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_origins_env.split(',') if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_origins_env.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://*.railway.app",
        "https://*.up.railway.app",
        "https://*.vercel.app",
    ]

REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
      ],
      'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Only the login/refresh views opt into throttling (see totem_backend/urls.py)
    # to slow down password guessing against /token/.
    'DEFAULT_THROTTLE_RATES': {
        'login': os.environ.get('LOGIN_THROTTLE_RATE', '30/min'),
    },
}

SIMPLE_JWT = {
     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=20),
     'REFRESH_TOKEN_LIFETIME': timedelta(hours=2),
     'ROTATE_REFRESH_TOKENS': True,
     'BLACKLIST_AFTER_ROTATION': True
}

MEDIA_ROOT = DATA_DIR / "user_files"
MEDIA_URL = "/files/"

# ---------------------------------------------------------------------------
# Request result cache (filesystem-backed, size-capped)  — Epic #71
# ---------------------------------------------------------------------------
RESULT_CACHE_DIR = DATA_DIR / "cache" / "results"
RESULT_CACHE_MAX_ENTRIES = int(os.environ.get("TOTEM_CACHE_MAX_ENTRIES", "300"))

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "results": {
        # LRU subclass of Django's FileBasedCache — the stock backend evicts a
        # random selection of entries at the size cap, which can discard hot
        # results while keeping cold ones.
        "BACKEND": "api.lru_filecache.LRUFileBasedCache",
        "LOCATION": str(RESULT_CACHE_DIR),
        "OPTIONS": {
            "MAX_ENTRIES": RESULT_CACHE_MAX_ENTRIES,
        },
        "TIMEOUT": None,  # no auto-expiry; evicted on size cap or explicit clear
    },
}

if LOCAL_MODE:
    SIMPLE_JWT = {
        'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
        'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
        'ROTATE_REFRESH_TOKENS': True,
        'BLACKLIST_AFTER_ROTATION': True,
    }

# Credentials used for the auto-seeded Guest account. The account is only
# created (and its password reset) in LOCAL_MODE, or when SEED_GUEST_USER=1
# is set explicitly for demo deployments.
LOCAL_GUEST_USERNAME = 'Guest'
LOCAL_GUEST_PASSWORD = 'guest'
SEED_GUEST_USER = LOCAL_MODE or os.environ.get('SEED_GUEST_USER', '0') == '1'