"""
Resource-aware process executions and variants on the tiny orders log.

The log (``test_data/small/resource_aware_orders.json``, generated by
``examples/generate_resource_aware_logs.py``) has four orders handled by one
worker who touches every object. Plain connected components therefore see one
execution; the resource-aware extraction, which only lets business objects and
business activities connect executions, sees three.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

from totem_lib.ocel.importer_db import import_ocel_db
from totem_lib.variants import (
    extract_process_executions,
    find_variants,
    partition_events,
    variant_assignment,
    variant_ids_by_case,
)
from totem_lib.variants.extraction import extract_cases

TEST_DATA = Path(__file__).parent.parent.parent / "test_data" / "small"
CLEAN_LOG = TEST_DATA / "resource_aware_orders.json"

BUSINESS_TYPES = ["order", "item", "package"]
BUSINESS_ACTIVITIES = ["place order", "pick item", "pack items", "ship package", "close order"]
SHIFT_EVENTS = {"e01", "e22"}


@pytest.fixture(scope="module")
def db():
    database = import_ocel_db(str(CLEAN_LOG))
    yield database
    database.close()


def test_worker_collapses_connected_components_but_not_resource_aware(db):
    connected = extract_process_executions(db, extraction="connected")
    resource_aware = extract_process_executions(
        db,
        extraction="resource_aware",
        business_object_types=BUSINESS_TYPES,
        business_activities=BUSINESS_ACTIVITIES,
    )

    assert connected.execution_count == 1
    assert resource_aware.execution_count == 3
    assert resource_aware.extraction == "resource_aware"

    # Executions are keyed by their smallest business object and contain the
    # business objects only -- the worker never becomes part of an execution.
    assert set(resource_aware.case_objects) == {"i1", "i3", "i5"}
    assert resource_aware.case_objects["i1"] == {"o1", "i1", "i2", "p1"}
    assert resource_aware.case_objects["i5"] == {"o3", "o4", "i5", "i6", "p3"}
    for objects in resource_aware.case_objects.values():
        assert "w1" not in objects

    # ... but every event of those objects belongs to the execution, ordered
    # by time, including the worker-assisted picks.
    assert resource_aware.case_events["i1"] == ["e02", "e04", "e05", "e06", "e07", "e08"]
    assert resource_aware.case_events["i5"] == [
        "e14", "e15", "e16", "e17", "e18", "e19", "e20", "e21",
    ]


def test_partition_leaves_worker_only_events_unassigned(db):
    executions = extract_process_executions(
        db,
        extraction="resource_aware",
        business_object_types=BUSINESS_TYPES,
        business_activities=BUSINESS_ACTIVITIES,
    )
    partition = partition_events(executions.case_events)

    assert partition.ambiguous_event_ids == frozenset()
    assert set(partition.assignment) == {f"e{i:02d}" for i in range(1, 23)} - SHIFT_EVENTS
    assert partition.assignment["e02"] == "i1"
    assert partition.assignment["e13"] == "i3"
    assert executions.event_count == 20


def test_excluding_a_business_activity_splits_executions_and_marks_shared_events(db):
    # Without "pack items" the package no longer links items of different
    # orders (or the two orders sharing p3), so o3 and o4 fall apart and the
    # shared pack event becomes ambiguous.
    executions = extract_process_executions(
        db,
        extraction="resource_aware",
        business_object_types=BUSINESS_TYPES,
        business_activities=[a for a in BUSINESS_ACTIVITIES if a != "pack items"],
    )
    partition = partition_events(executions.case_events)

    assert executions.case_objects["i5"] == {"o3", "i5"}
    assert executions.case_objects["i6"] == {"o4", "i6"}
    assert executions.case_objects["p3"] == {"p3"}
    assert "e18" in partition.ambiguous_event_ids  # pack items: p3 + i5 + i6
    assert partition.assignment["e19"] == "p3"      # ship package: p3 only


def test_business_activities_default_to_every_activity(db):
    executions = extract_process_executions(
        db, extraction="resource_aware", business_object_types=BUSINESS_TYPES
    )
    assert executions.execution_count == 3


def test_extraction_validation():
    import duckdb
    from totem_lib.ocel.ocel_duckdb import create_ocel_schema

    conn = duckdb.connect(":memory:")
    create_ocel_schema(conn, [], [])
    with pytest.raises(ValueError, match="business object type"):
        extract_cases(conn, "resource_aware", business_object_types=[])
    with pytest.raises(ValueError, match="business_activities"):
        extract_cases(conn, "resource_aware", business_object_types=["order"], business_activities=[])
    with pytest.raises(ValueError, match="leading_type"):
        extract_cases(conn, "leading_1hop")
    with pytest.raises(ValueError, match="unknown extraction"):
        extract_cases(conn, "nope")


def test_resource_aware_variants_group_isomorphic_executions(db):
    variants = find_variants(
        db,
        extraction="resource_aware",
        business_object_types=BUSINESS_TYPES,
        business_activities=BUSINESS_ACTIVITIES,
        iso="wl+vf2",
        verbose=False,
    )

    assert [v.support for v in variants] == [2, 1]
    by_support = {v.support: v for v in variants}
    assert sorted(by_support[2].case_ids) == ["i1", "i3"]
    assert by_support[1].case_ids == ["i5"]

    # The worker induces no edges: the representative graphs only know the
    # business objects of their execution.
    for variant in variants:
        objects = {o for _, _, data in variant.graph.edges(data=True) for o in data["objects"]}
        assert "w1" not in objects
        assert objects


def test_find_variants_accepts_pre_extracted_cases(db):
    executions = extract_process_executions(
        db,
        extraction="resource_aware",
        business_object_types=BUSINESS_TYPES,
        business_activities=BUSINESS_ACTIVITIES,
    )
    variants = find_variants(
        db, extraction="resource_aware", cases=executions.case_objects, verbose=False
    )
    assert [v.support for v in variants] == [2, 1]

    by_case = variant_ids_by_case(variants)
    assert set(by_case) == {"i1", "i3", "i5"}
    assert by_case["i1"] == by_case["i3"] != by_case["i5"]

    assignment = variant_assignment(partition_events(executions.case_events), variants)
    assert set(assignment) == set(partition_events(executions.case_events).assignment)
    assert assignment["e02"] == assignment["e13"]


def test_find_variants_requires_business_object_types(db):
    with pytest.raises(ValueError, match="business_object_types"):
        find_variants(db, extraction="resource_aware", verbose=False)
    with pytest.raises(ValueError, match="unknown extraction"):
        find_variants(db, extraction="resource-aware", verbose=False)
