name: Build and Test Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-totem-lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        sed -i '/totem_lib/d' totem_lib/requirements.txt
        pip install -r totem_lib/requirements.txt
        pip install -e totem_lib
    - name: Test with pytest
      working-directory: ./totem_lib
      run: pytest

  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sed -i '/totem_lib/d' totem_lib/requirements.txt
        pip install -r totem_lib/requirements.txt
        pip install -e totem_lib
        pip install -r backend/requirements.txt
    - name: Run Django tests
      run: python backend/manage.py test

  build-frontend-no-typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install
    - name: Build (no typecheck)
      working-directory: ./frontend
      run: npm run build-no-typecheck
